name: End-to-end tests

on: [push]
jobs:
  cypress-run:
    runs-on: ubuntu-20.04
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Set ServiceAccount
        run: 'echo "$GCP_SA" > bonout-web-app-sa.json'
        shell: bash
        env:
          GCP_SA: ${{secrets.GCP_SA}}
      # Install NPM dependencies, cache them correctly
      # and run all Cypress tests
      - name: Cypress run
        uses: cypress-io/github-action@v2
        with:
          build: yarn run build
          start: yarn run start
          wait-on: http://localhost:3000
        env:
          CYPRESS_PROJECT_ID: ${{ secrets.CYPRESS_PROJECT_ID }}
          CYPRESS_RECORD_KEY: ${{ secrets.CYPRESS_RECORD_KEY }}
          DB_ENV: staging
