name: deploy-staging
on:
  push:
    branches:
      - main

env:
  PROJECT_ID: ${{ secrets.GCP_PROJECT_ID }}
  GITHUB_TOKEN: ${{ secrets.GH_TOKEN }}
  SERVICE: web-app-staging
  REGION: europe-west1

jobs:
  setup-build-publish-deploy:
    name: Setup, Build, Publish, and Deploy
    runs-on: ubuntu-20.04
    steps:
    - name: Checkout
      uses: actions/checkout@v2

    - id: auth
      uses: google-github-actions/auth@v0.4.1
      with:
        workload_identity_provider: 'projects/123456789/locations/global/workloadIdentityPools/my-pool/providers/my-provider'
        service_account: 'my-service-account@my-project.iam.gserviceaccount.com'

    # Setup gcloud CLI
    - name: Set up Cloud SDK
      uses: google-github-actions/setup-gcloud@v0.3.0

    - name: Authorize Docker push
      run: gcloud auth configure-docker

    - name: Build and Push Container
      run: |-
        docker build -t eu.gcr.io/${{ env.PROJECT_ID }}/web-app/${{ env.SERVICE }}:${{  github.sha }} .
        docker push eu.gcr.io/${{ env.PROJECT_ID }}/web-app/${{ env.SERVICE }}:${{  github.sha }}

    - uses: chrnorm/deployment-action@releases/v1
      name: Create GitHub deployment on staging
      id: deployment
      with:
        token: "${{ env.GITHUB_TOKEN }}"
        target_url: https://staging.bonout.com
        environment: staging

    - name: Deploy to Cloud Run
      run: |-
        gcloud run deploy ${{ env.SERVICE }} \
          --region ${{ env.REGION }} \
          --image eu.gcr.io/${{ env.PROJECT_ID }}/web-app/${{ env.SERVICE }}:${{  github.sha }} \
          --platform "managed" \
          --quiet

    - name: Update deployment status (success)
      if: success()
      uses: chrnorm/deployment-status@releases/v1
      with:
        token: "${{ env.GITHUB_TOKEN }}"
        target_url: https://staging.bonout.com
        state: "success"
        deployment_id: ${{ steps.deployment.outputs.deployment_id }}

    - name: Discord notification
      env:
        DISCORD_WEBHOOK: ${{ secrets.DISCORD_WEBHOOK }}
      uses: Ilshidur/action-discord@master
      with:
        args: 'The project {{ EVENT_PAYLOAD.repository.full_name }} has been deployed to staging.'
