name: Jest tests

on: [pull_request]

jobs:
  jest-tests:
    name: Jest test:ci
    runs-on: ubuntu-20.04
    steps:
    - name: Test
      uses: willcaul/jest-github-action@v2
      env:
        GITHUB_TOKEN: ${{ secrets.GH_TOKEN }}
        DB_ENV: staging
      with:
        test-command: 'npm run test:ci -- --testLocationInResults --json --coverage --outputFile="jest.results.json"'
