name: Jest tests

on: [pull_request]

jobs:
  jest-tests:
    name: Jest test:ci
    runs-on: ubuntu-20.04
    steps:
    - name: Checkout
      uses: actions/checkout@v2
    - name: Cache pnpm modules
      uses: actions/cache@v2
      with:
        path: ~/.pnpm-store
        key: ${{ runner.os }}-${{ hashFiles('**/pnpm-lock.yaml') }}
        restore-keys: |
          ${{ runner.os }}-
    - uses: pnpm/action-setup@v2.0.1
      with:
        version: 6.0.2
        run_install: true
    - name: run build
      run: pnpm run build
      env:
        DB_ENV: staging
    - name: run test:ci
      uses: mattallty/jest-github-action@v1
      env:
        GITHUB_TOKEN: ${{ secrets.GH_TOKEN }}
      with:
        test-command: "pnpm run test:ci"
        coverage-comment: false
