name: End-to-end tests

on: [push]
jobs:
  cypress-run:
    runs-on: ubuntu-20.04
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Set ServiceAccount
        run: 'echo "$GCP_SA" > bonout-web-app-sa.json'
        shell: bash
        env:
          GCP_SA: ${{secrets.GCP_SA}}
      - name: Cache pnpm modules
        uses: actions/cache@v2
        with:
          path: ~/.pnpm-store
          key: ${{ runner.os }}-${{ hashFiles('**/pnpm-lock.yaml') }}
          restore-keys: |
            ${{ runner.os }}-
      - uses: pnpm/action-setup@v2.0.1
        with:
          version: 6.0.2
          run_install: true
      - name: test run
        with:
          build: pnpm run build
          start: pnpm run start
          wait-on: http://localhost:3000
        env:
          DB_ENV: staging
